version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: chemist_task_db
    environment:
      MYSQL_ROOT_PASSWORD: '@12345Admin'
      MYSQL_DATABASE: 'chemist_task_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '@12345Admin'
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: chemist_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: '@12345Admin'
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: 